spring.application.name=ecotwin-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecotwin
spring.datasource.username=sahith
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
